application: scanmybar
version: change-me
runtime: python27
api_version: 1
threadsafe: true

default_expiration: 0

handlers:
- url: /.*
  script: main.app

skip_files: |
 ^(.*/)?(
 (\..*)|
 (.*\.pyc)|
 )$
